### Heavily based on ["10 Minutes to pandas"](https://pandas.pydata.org/pandas-docs/stable/10min.html)

In [1]:
import pandas as pd

import numpy as np

# Series, DataFrames

In [2]:
# a pandas series is a vector of data, a column
s = pd.Series([1,3,5,np.nan,6,8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [3]:
# a DataFrame is a data table, always indexed.
# creating one from a random numpy 2D array (notice the index isn't specified, automatically becomes zero based counter):
df = pd.DataFrame(np.random.randn(6,4), columns = ['A', 'B', 'C', 'D'])
print(df)

          A         B         C         D
0  0.276083  1.166528  0.093775 -0.112009
1 -0.806349  1.807758 -0.260645 -0.123259
2  0.625757 -0.506556  0.825958 -0.240297
3 -2.732960  0.295680  0.701168  1.680807
4  0.550647  0.546785 -0.525854  0.139442
5  1.105849  1.031903  2.106953  0.232958


In [4]:
# creating a DataFrame from a very varied dictionary where each key is a column (also see pd.from_dict()):
df2 = pd.DataFrame({'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1, index = list(range(4)), dtype = 'float32'),
                    'D' : np.array(np.arange(4), dtype = 'int32'),
                    'E' : pd.Categorical(["test", "train", "test", "train"]),
                    'F' : 'foo' })
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  0   test  foo
1  1.0 2013-01-02  1.0  1  train  foo
2  1.0 2013-01-02  1.0  2   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [5]:
# looking at the DataFrame columns types (notice this is a Series!):
print(df2.dtypes)

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


In [6]:
# reading from CSV
df3 = pd.read_csv("../../datasets/test.csv")
print(df3)

   x   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10


# Some info

In [7]:
# get top rows
print(df.head())

          A         B         C         D
0  0.276083  1.166528  0.093775 -0.112009
1 -0.806349  1.807758 -0.260645 -0.123259
2  0.625757 -0.506556  0.825958 -0.240297
3 -2.732960  0.295680  0.701168  1.680807
4  0.550647  0.546785 -0.525854  0.139442


In [8]:
# get bottom rows
print(df.tail(2))

          A         B         C         D
4  0.550647  0.546785 -0.525854  0.139442
5  1.105849  1.031903  2.106953  0.232958


In [9]:
# view index
print(df.index)

RangeIndex(start=0, stop=6, step=1)


In [10]:
# view column names
print(df.columns)

Index(['A', 'B', 'C', 'D'], dtype='object')


In [11]:
# get the underlying numpy matrix
print(df.values)

[[ 0.27608278  1.16652818  0.09377536 -0.11200937]
 [-0.80634931  1.80775777 -0.26064452 -0.12325945]
 [ 0.62575723 -0.50655584  0.8259579  -0.24029671]
 [-2.73295986  0.29567963  0.70116833  1.68080679]
 [ 0.55064728  0.54678524 -0.52585358  0.13944225]
 [ 1.10584887  1.031903    2.10695288  0.23295768]]


In [12]:
# quick statistics summary
print(df.describe())

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.163496  0.723683  0.490226  0.262940
std    1.410872  0.799287  0.951253  0.716866
min   -2.732960 -0.506556 -0.525854 -0.240297
25%   -0.535741  0.358456 -0.172040 -0.120447
50%    0.413365  0.789344  0.397472  0.013716
75%    0.606980  1.132872  0.794761  0.209579
max    1.105849  1.807758  2.106953  1.680807


In [13]:
# transposing a DataFrame
print(df.T)

          0         1         2         3         4         5
A  0.276083 -0.806349  0.625757 -2.732960  0.550647  1.105849
B  1.166528  1.807758 -0.506556  0.295680  0.546785  1.031903
C  0.093775 -0.260645  0.825958  0.701168 -0.525854  2.106953
D -0.112009 -0.123259 -0.240297  1.680807  0.139442  0.232958


In [14]:
# sorting by column names
print(df.sort_index(axis = 1, ascending = False))

          D         C         B         A
0 -0.112009  0.093775  1.166528  0.276083
1 -0.123259 -0.260645  1.807758 -0.806349
2 -0.240297  0.825958 -0.506556  0.625757
3  1.680807  0.701168  0.295680 -2.732960
4  0.139442 -0.525854  0.546785  0.550647
5  0.232958  2.106953  1.031903  1.105849


In [15]:
# sorting by a specific column values
print(df.sort_values(by = 'B'))

          A         B         C         D
2  0.625757 -0.506556  0.825958 -0.240297
3 -2.732960  0.295680  0.701168  1.680807
4  0.550647  0.546785 -0.525854  0.139442
5  1.105849  1.031903  2.106953  0.232958
0  0.276083  1.166528  0.093775 -0.112009
1 -0.806349  1.807758 -0.260645 -0.123259


# Selection

In [16]:
# select a specific column (this will give you a Series!) - pandas people do not recommend this, see loc/iloc
print(df['A'])

0    0.276083
1   -0.806349
2    0.625757
3   -2.732960
4    0.550647
5    1.105849
Name: A, dtype: float64


In [17]:
# slicing rows as in a numpy array - pandas people do not recommend this, see loc/iloc
print(df[0:3])
print(df.T['A':'B'])

          A         B         C         D
0  0.276083  1.166528  0.093775 -0.112009
1 -0.806349  1.807758 -0.260645 -0.123259
2  0.625757 -0.506556  0.825958 -0.240297
          0         1         2        3         4         5
A  0.276083 -0.806349  0.625757 -2.73296  0.550647  1.105849
B  1.166528  1.807758 -0.506556  0.29568  0.546785  1.031903


### Selection by label (`loc`)

In [18]:
# select a specific column, all rows
print(df.loc[:, 'A'])

0    0.276083
1   -0.806349
2    0.625757
3   -2.732960
4    0.550647
5    1.105849
Name: A, dtype: float64


In [19]:
# select first 2 rows, specific two columns
print(df.loc[0:1, ['A', 'B']])

          A         B
0  0.276083  1.166528
1 -0.806349  1.807758


In [20]:
# select specific value
print(df.loc[0, 'A'])

# but "at" is preferred
print(df.at[0, 'A'])

0.276082784697
0.276082784697


### Selection by position (`iloc`)

In [21]:
# specific row (as a Series)
print(df.iloc[3])

A   -2.732960
B    0.295680
C    0.701168
D    1.680807
Name: 3, dtype: float64


In [22]:
# specific row (as a sub-table)
print(df.iloc[3:4, :])

         A        B         C         D
3 -2.73296  0.29568  0.701168  1.680807


In [23]:
# sub-table
print(df.iloc[3:5, 0:2])

          A         B
3 -2.732960  0.295680
4  0.550647  0.546785


In [24]:
# integer indexing
print(df.iloc[[1,2,4], [0,2]])

          A         C
1 -0.806349 -0.260645
2  0.625757  0.825958
4  0.550647 -0.525854


### Boolean indexing

In [25]:
# filter only values answering condition in specific column
print(df[df.A > 0])

          A         B         C         D
0  0.276083  1.166528  0.093775 -0.112009
2  0.625757 -0.506556  0.825958 -0.240297
4  0.550647  0.546785 -0.525854  0.139442
5  1.105849  1.031903  2.106953  0.232958


In [26]:
# if not using specific column...
print(df[df > 0])

          A         B         C         D
0  0.276083  1.166528  0.093775       NaN
1       NaN  1.807758       NaN       NaN
2  0.625757       NaN  0.825958       NaN
3       NaN  0.295680  0.701168  1.680807
4  0.550647  0.546785       NaN  0.139442
5  1.105849  1.031903  2.106953  0.232958


# Setting

In [27]:
# set a new column s1
s1 = pd.Series([1,2,3,4,5,6])
df['E'] = s1
print(df)

          A         B         C         D  E
0  0.276083  1.166528  0.093775 -0.112009  1
1 -0.806349  1.807758 -0.260645 -0.123259  2
2  0.625757 -0.506556  0.825958 -0.240297  3
3 -2.732960  0.295680  0.701168  1.680807  4
4  0.550647  0.546785 -0.525854  0.139442  5
5  1.105849  1.031903  2.106953  0.232958  6


In [28]:
# set a specific value
df.at[0, 'A'] = 0
print(df)

          A         B         C         D  E
0  0.000000  1.166528  0.093775 -0.112009  1
1 -0.806349  1.807758 -0.260645 -0.123259  2
2  0.625757 -0.506556  0.825958 -0.240297  3
3 -2.732960  0.295680  0.701168  1.680807  4
4  0.550647  0.546785 -0.525854  0.139442  5
5  1.105849  1.031903  2.106953  0.232958  6


In [29]:
# set a whole column with numpy
df.loc[:, 'D'] = np.array([5] * len(df))
print(df)

          A         B         C  D  E
0  0.000000  1.166528  0.093775  5  1
1 -0.806349  1.807758 -0.260645  5  2
2  0.625757 -0.506556  0.825958  5  3
3 -2.732960  0.295680  0.701168  5  4
4  0.550647  0.546785 -0.525854  5  5
5  1.105849  1.031903  2.106953  5  6


In [30]:
# set with boolean indexing
df[df < 0] = np.nan
print(df)

          A         B         C  D  E
0  0.000000  1.166528  0.093775  5  1
1       NaN  1.807758       NaN  5  2
2  0.625757       NaN  0.825958  5  3
3       NaN  0.295680  0.701168  5  4
4  0.550647  0.546785       NaN  5  5
5  1.105849  1.031903  2.106953  5  6


# Missing Data

In [31]:
# dropping rows with any missing data (see documentation for more)
df1 = df.copy()
print(df1.dropna(how = 'any'))

          A         B         C  D  E
0  0.000000  1.166528  0.093775  5  1
5  1.105849  1.031903  2.106953  5  6


In [32]:
# filling missing values with a specific value
print(df1.fillna(value = 5))

          A         B         C  D  E
0  0.000000  1.166528  0.093775  5  1
1  5.000000  1.807758  5.000000  5  2
2  0.625757  5.000000  0.825958  5  3
3  5.000000  0.295680  0.701168  5  4
4  0.550647  0.546785  5.000000  5  5
5  1.105849  1.031903  2.106953  5  6


In [33]:
# getting a boolean mask of where missing values are (similar to R)
print(pd.isna(df1))

       A      B      C      D      E
0  False  False  False  False  False
1   True  False   True  False  False
2  False   True  False  False  False
3   True  False  False  False  False
4  False  False   True  False  False
5  False  False  False  False  False


# Basic Operations

In [34]:
# apply mean to each column
print(df.mean())

A    0.570563
B    0.969731
C    0.931964
D    5.000000
E    3.500000
dtype: float64


In [35]:
# apply sum to each row
print(df.sum(axis = 1))

0     7.260304
1     8.807758
2     9.451715
3     9.996848
4    11.097433
5    15.244705
dtype: float64


In [36]:
# df.apply a non-pandas function
print(df.apply(np.cumsum))

          A         B         C   D   E
0  0.000000  1.166528  0.093775   5   1
1       NaN  2.974286       NaN  10   3
2  0.625757       NaN  0.919733  15   6
3       NaN  3.269966  1.620902  20  10
4  1.176405  3.816751       NaN  25  15
5  2.282253  4.848654  3.727854  30  21


In [37]:
# apply anonumous function
print(df.apply(lambda x: x.max() - x.min()))

A    1.105849
B    1.512078
C    2.013178
D    0.000000
E    5.000000
dtype: float64


# Basic Manipulation

pandas is inspired by R's `tidyverse` philosophy and works best with "tidy", long datasets, in which every column is a single variable, and every row is a single observation.

In [38]:
# group by a categorical variable, and get mean by group for all numeric variables
df2 = pd.DataFrame({'categorical': np.tile(['A', 'B'], (5, )),
                    'numerical1': np.random.randn(10),
                    'numerical2': 10 + 2 * np.random.randn(10)})
df2.groupby('categorical').mean()

numerical1  numerical2
categorical                        
A             -0.680441    7.564722
B              0.079634   10.644356

### See more in documentation